module.exports = {
  InvalidAuthInfo:{code:'InvalidAuthInfo',message:'密码错误或手机号未注册'},
  WrongPassword:{code:'WrongPassword',message:'密码错误'},
  PermissionDenied:{code:'PermissionDenied',message:'您的权限不足以完成此操作'},
  AddingSelfAsRelative:{code:'AddingSelfAsRelative',message:'不能添加自己为亲人'},
  KinshipExisted:{code:'KinshipExisted',message:'双方已经是亲人关系'},
  EcgRelativeNumberReachedLimit:{code:'EcgRelativeNumberReachedLimit',message:'您的亲友数量已经到达上限'},
  InsufficientCredits:{code:'InsufficientCredits',message:'余额不足'},
  MissingParameter:{code:'MissingParameter',message:'缺少必需参数'},
  NameMismatch:{code:'NameMismatch',message:'患者名字不吻合'},
  NonexistentPayer:{code:'NonexistentPayer',message:'代付用户不存在'},
  ParameterValidationFailed:{code:'ParameterValidationFailed',message:'上传的参数格式验证失败'},
  ResourceInWrongState:{code:'ResourceInWrongState',message:'资源的状态与预期不同, 无法完成操作'},
  PhoneRegistered:{code:'PhoneRegistered',message:'该手机号已被注册'},
  UsernameRegistered:{code:'UsernameRegistered',message:'该用户名已被注册'},
  DeviceBindedToSelf:{code:'DeviceBindedToSelf',message:'用户已绑定过该设备'},
  DeviceBindedToOther:{code:'DeviceBindedToOther',message:'设备已和其他用户绑定'},
  RepNotRegistered:{code:'RepNotRegistered',message:'该微信openid尚未注册'},
  PhoneNotRegistered:{code:'PhoneNotRegistered',message:'该手机号尚未注册'},
  RepRegistered:{code:'RepRegistered',message:'该微信openid已被注册'},
  WrongVerificationCode:{code:'WrongVerificationCode',message:'验证码错误'},
  DoctorBookmarked:{code:'DoctorBookmarked',message:'已经关注过此医生'},
  DoctorNotFound:{code:'DoctorNotFound',message:'没有找到对应的医生'},
  PatientNotFound:{code:'PatientNotFound',message:'没有找到对应的患者'},
  ResourceNotFound:{code:'ResourceNotFound',message:'没有找到匹配的资源'},
  PasswordTooShort:{code:'PasswordTooShort',message:'密码不能短于5位'},
  PasswordTooLong:{code:'PasswordTooLong',message:'密码不能长于25位'},
  SpaceInPassword:{code:'SpaceInPassword',message:'密码不能包含空格'},
  DoctorAlreadyInquired:{code:'DoctorAlreadyInquired',message:'之前发送给这位医生的请求尚未处理, 请勿重复提问'},
  InvalidQRCodeAction:{code:'InvalidQRCodeAction',message:'无法识别该二维码类别'},
  InvalidQRCode:{code:'InvalidQRCode',message:'无法识别该二维码'},
  PatientAlreadyFollowedUp:{code:'PatientAlreadyFollowedUp',message:'该患者已在医生的随诊列表中'},
  IllegalCharInWenanId:{code:'IllegalCharInWenanId',message:'问安号只能包含字母和数字'},
  WenanIdAlreadyTaken:{code:'WenanIdAlreadyTaken',message:'该问安号已被占用'},
  DoctorAlreadyFollowed:{code:'DoctorAlreadyFollowed',message:'已经关注了该医生'},
  NoEcgRequestAvailable:{code:'NoEcgRequestAvailable',message:'心电图已经被抢光啦! 请稍后再试~'},
  AccessTokenExpired:{code:'AccessTokenExpired',message:'access-token已过期'}
}
